name: Continuous Integration

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 16.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0

      - name: Install packages
        run: yarn install

      - name: Run Makefile deploy
        run: |
          git config --global user.name "nenewang"
          make build-commit-donpush

      - name: Pushing Changes
        run: make ft-configpush
