name: Continuous Integration
on:
  workflow_dispatch:
jobs:
  install-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run Makefile deploy
        run: |
          git config --global user.name "nenewang"
          make build-commit-donpush
          make ft-configpush
