name: Continuous Integration
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - name: Run Makefile deploy
        run: |
          git config --global user.name "nenewang"
          make build-commit-donpush
          make ft-configpush
